# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea28332a0dee608914c57bde9417706b23304c577ac3e987ce1b85836d75861e3b43b72fef79f8688c6c8e3a116413344c7faf0d152c7ab6e695f3d8b61d2b38
  facebook_app_id: 151385155278830
  facebook_app_secret: 1e1fa184d950224775324e61e7578fed
test:
  secret_key_base: b0b8a2e951f32441189a5a9b68abbb9d42f6b2778069fa8a488249530dbc0a3999b419f0e7adc06a64e9f5c18c78e82eb42daf8907ab397986e06fa0c506caf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
